version: '1.0'
name: update-metadata
displayName: auto-update
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
variables:
  global:
    - ACCESS_TOKEN
stages:
  - name: stage-5f7636e6
    displayName: 执行脚本
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 执行脚本生成 metadata.json readme'
          - node ./auto-update.js
          - ''
          - '# 规避 流水线不同阶段的工作目录隔离 '
          - '# 配置 Git 身份（必须与令牌所有者一致）'
          - git config --global user.name "geoffwo"
          - git config --global user.email "geoffwo@gmail.com"
          - ''
          - '# 提交变更'
          - 'git add .   # 添加所有变更文件（包括 JS 和 metadata.json）'
          - git commit -m "[ci skip] Auto-update metadata&readme" || echo "No changes to commit"
          - ''
          - '# 使用 HTTPS + 令牌推送'
          - git push https://Geoffwo:$ACCESS_TOKEN@gitee.com/Geoffwo/rule-process-plugin.git master
        caches: []
        notify: []
        strategy:
          retry: '0'
