version: '1.0'
name: update-metadata
displayName: update-metadata
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
variables:
  global:
    - TOKEN
stages:
  - name: stage-5f7636e6
    displayName: 执行脚本
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 执行脚本生成 metadata.json'
          - node ./update-metadata.js
          - git config --global user.name "github-actions"
          - git config --global user.email "actions@github.com"
          - git add metadata.json
          - git commit -m "Auto-update metadata" || echo "No changes to commit"
          - git push
        caches: []
        notify: []
        strategy:
          retry: '0'
