version: '1.0'
name: update-metadata
displayName: update-metadata
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-5f7636e6
    displayName: 执行脚本
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 执行脚本生成 metadata.json'
          - node ./update-metadata.js
          - git add metadata.json       # 建议补充此行，确保 metadata.json 被提交
          - git commit -m "auto: 自动更新metadata.json" || echo "无变更"  # 提交更改，无变更时不报错
          - git push                   # 推送到远程仓库
        caches: []
        notify: []
        strategy:
          retry: '0'
